/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Stream
         * @description 단계별 진행을 SSE 로 흘린다.
         *
         *     토큰 단위 스트리밍이 아니라 **파이프라인 단계** 스트리밍이다. 이 파이프라인에서
         *     기다리게 만드는 것은 토큰 생성이 아니라 검색과 검증이고, 진행 중에 알고 싶은
         *     것도 "지금 어느 단계인가" 이기 때문이다.
         */
        post: operations["generate_stream_generate_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Index
         * @description 데모 숙소를 생성해 색인한다.
         *
         *     인덱스 구조 자체는 매번 다시 만든다. 비싼 것은 그쪽이 아니라 임베딩이고,
         *     콘텐츠 해시가 같은 청크는 디스크 캐시에서 나오므로 ``embedded`` 가 0에 가깝다.
         *     숙소 한 곳만 바뀌었을 때는 ``PropertyIndexer.upsert`` 가 그 청크만 건드린다.
         */
        post: operations["build_index_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ContentFormat
         * @enum {string}
         */
        ContentFormat: "SNS" | "AD_COPY" | "CRM";
        /** GenerateRequest */
        GenerateRequest: {
            format: components["schemas"]["ContentFormat"];
            /** Property Id */
            property_id: string;
            segment: components["schemas"]["Segment"];
        };
        /** GenerateResponse */
        GenerateResponse: {
            /** Attempts */
            attempts: number;
            /** Backend */
            backend: string;
            /** Content */
            content: string;
            format: components["schemas"]["ContentFormat"];
            /** Property Id */
            property_id: string;
            segment: components["schemas"]["Segment"];
            /** Valid */
            valid: boolean;
            /** Violations */
            violations?: components["schemas"]["ViolationOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HitOut */
        HitOut: {
            /** Chunk Id */
            chunk_id: string;
            /** Doc Type */
            doc_type: string;
            /** Property Id */
            property_id: string;
            /** Score */
            score: number;
            /** Text */
            text: string;
        };
        /** IndexRequest */
        IndexRequest: {
            /** Count */
            count?: number | null;
            /** Seed */
            seed?: number | null;
        };
        /** IndexResponse */
        IndexResponse: {
            /** Added */
            added: number;
            /** Embedded */
            embedded: number;
            /** Properties */
            properties: number;
            /** Removed */
            removed: number;
            /** Unchanged */
            unchanged: number;
            /** Updated */
            updated: number;
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Backend */
            backend: string;
            /** Chunks */
            chunks: number;
            /** Embedding Cache */
            embedding_cache: {
                [key: string]: unknown;
            };
            /** Indexed */
            indexed: boolean;
            /** Properties */
            properties: number;
            /** Thresholds */
            thresholds: {
                [key: string]: unknown;
            };
        };
        /**
         * PropertyType
         * @enum {string}
         */
        PropertyType: "APARTMENT" | "HOTEL" | "GUESTHOUSE" | "PENSION" | "HOUSE";
        /** SearchRequest */
        SearchRequest: {
            /** Max Price */
            max_price?: number | null;
            /** Min Capacity */
            min_capacity?: number | null;
            property_type?: components["schemas"]["PropertyType"] | null;
            /** Query */
            query: string;
            /** Region */
            region?: string | null;
            /** Required Amenities */
            required_amenities?: string[];
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Candidates After Filter */
            candidates_after_filter: number;
            /** Candidates Before Filter */
            candidates_before_filter: number;
            /** Filter Reduction */
            filter_reduction: number;
            /** Grounded */
            grounded: boolean;
            /** Hits */
            hits: components["schemas"]["HitOut"][];
            /** Reason */
            reason?: string | null;
        };
        /**
         * Segment
         * @enum {string}
         */
        Segment: "COUPLE" | "FAMILY" | "BUSINESS";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ViolationOut */
        ViolationOut: {
            /** Detail */
            detail: string;
            /** Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_stream_generate_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    build_index_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IndexRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
    search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
