/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast/low-demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Low Demand
         * @description 수요가 낮게 예측된 숙소·날짜.
         *
         *     콘솔과 조정자가 이걸 받아 개입 대상으로 넘긴다.
         *
         *     **예측값과 그 구간의 오차를 같이 낸다.** 낮은 예측 하나만으로는 행동할 수
         *     없다는 것을 스키마가 강제한다 — 소비자가 오차를 안 보고 결정하려면 필드를
         *     일부러 무시해야 하고, 그건 코드에 흔적이 남는다.
         *
         *     거르지는 않는다. "WAPE 가 높으니 이 행은 빼자" 는 **소비자의 정책**이지
         *     예측 서비스가 대신 정할 일이 아니다. 여기서 걸러 버리면 조정자는 자기가 무엇을
         *     못 봤는지조차 모른다.
         */
        get: operations["low_demand_forecast_low_demand_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Segments
         * @description 세그먼트별 오차.
         *
         *     전체 WAPE 만 보면 희박한 구간이 가려진다. 평균 뒤에 무엇이 숨어 있는지를
         *     같이 내보내는 게 이 프로젝트의 규칙이라 API 에서도 그대로 한다.
         *
         *     **축이 하나면 그 규칙이 반쪽이다.** 지역만 볼 수 있으면 특정 숙소 유형에서만
         *     무너지는 모델을 지역 평균이 덮어 가린다. 그래서 축을 파라미터로 연다.
         */
        get: operations["segments_forecast_segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ForecastResponse */
        ForecastResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Count */
            count: number;
            /** Horizon Days */
            horizon_days: number;
            /** Model */
            model: string;
            /** Rows */
            rows: components["schemas"]["ForecastRow"][];
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
        };
        /** ForecastRow */
        ForecastRow: {
            /** Actual */
            actual?: number | null;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Predicted */
            predicted: number;
            /** Property Id */
            property_id: string;
            /** Property Type */
            property_type: string;
            /** Region */
            region: string;
            /**
             * Stay Date
             * Format: date
             */
            stay_date: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LowDemandResponse */
        LowDemandResponse: {
            /** Count */
            count: number;
            /**
             * Measured On
             * Format: date
             * @description 오차를 잰 검증 구간의 시작일
             */
            measured_on: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Rows */
            rows: components["schemas"]["LowDemandRow"][];
            /**
             * Threshold
             * @description 이 값 미만을 낮은 수요로 본다
             */
            threshold: number;
        };
        /**
         * LowDemandRow
         * @description 수요가 낮게 예측된 숙소·날짜 하나.
         *
         *     **예측값만 실어 보내지 않는다.** 이 응답의 소비자는 사람이 아니라 조정자이고,
         *     조정자는 이 행을 받아 할인을 승인할지 사람에게 넘길지를 정한다. 그런데
         *     "0.4개 예약" 이라는 숫자 하나만으로는 그 결정을 할 수 없다 — 그 구간에서
         *     모델이 평균 40% 씩 틀린다면 0.4 는 사실상 아무 말도 아니기 때문이다.
         *
         *     그래서 그 구간의 오차를 **같이 싣는다.** 옵션이 아니라 필수 필드다.
         */
        LowDemandRow: {
            /** Predicted */
            predicted: number;
            /** Property Id */
            property_id: string;
            /** Region */
            region: string;
            /**
             * Region N
             * @description 이 지역의 검증 표본 수
             */
            region_n: number;
            /**
             * Region Wape
             * @description 이 지역의 WAPE. null 이면 잴 표본이 없었다는 뜻 — 0 이 아니다
             */
            region_wape: number | null;
            /**
             * Stay Date
             * Format: date
             */
            stay_date: string;
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Baseline */
            baseline: string;
            /** Measured By */
            measured_by: string;
            /** Rows */
            rows: components["schemas"]["ModelRow"][];
            /** Serving */
            serving: string;
        };
        /** ModelRow */
        ModelRow: {
            /** Folds */
            folds: number;
            /** Mae Mean */
            mae_mean: number;
            /** Model */
            model: string;
            /** Vs Baseline Pct */
            vs_baseline_pct?: number | null;
            /** Wape Mean */
            wape_mean: number;
            /** Wape Std */
            wape_std: number;
            /** Wape Worst */
            wape_worst: number;
        };
        /** SegmentResponse */
        SegmentResponse: {
            /** Dimension */
            dimension: string;
            /** Model */
            model: string;
            /** Note */
            note: string;
            /** Rows */
            rows: components["schemas"]["SegmentRow"][];
        };
        /** SegmentRow */
        SegmentRow: {
            /** Key */
            key: string;
            /** Mae */
            mae: number;
            /** N */
            n: number;
            /** Rmse */
            rmse: number;
            /** Wape */
            wape: number;
            /** Zero Ratio */
            zero_ratio: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forecast_forecast_get: {
        parameters: {
            query?: {
                /** @description 지역으로 거른다 */
                region?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    low_demand_forecast_low_demand_get: {
        parameters: {
            query?: {
                /** @description 이 값 미만을 낮은 수요로 본다 */
                threshold?: number;
                region?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LowDemandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segments_forecast_segments_get: {
        parameters: {
            query?: {
                /** @description 쪼갤 축. region | property_type */
                by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
}
