/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast/low-demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Low Demand
         * @description 수요가 낮게 예측된 숙소·날짜.
         *
         *     콘솔이 이걸 받아 콘텐츠 생성으로 넘긴다.
         */
        get: operations["low_demand_forecast_low_demand_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Segments
         * @description 지역별 오차.
         *
         *     전체 WAPE 만 보면 희박한 지역이 가려진다. 평균 뒤에 무엇이 숨어 있는지를
         *     같이 내보내는 게 이 프로젝트의 규칙이라 API 에서도 그대로 한다.
         */
        get: operations["segments_forecast_segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ForecastResponse */
        ForecastResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Count */
            count: number;
            /** Horizon Days */
            horizon_days: number;
            /** Model */
            model: string;
            /** Rows */
            rows: components["schemas"]["ForecastRow"][];
            /**
             * Window End
             * Format: date
             */
            window_end: string;
            /**
             * Window Start
             * Format: date
             */
            window_start: string;
        };
        /** ForecastRow */
        ForecastRow: {
            /** Actual */
            actual?: number | null;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Predicted */
            predicted: number;
            /** Property Id */
            property_id: string;
            /** Property Type */
            property_type: string;
            /** Region */
            region: string;
            /**
             * Stay Date
             * Format: date
             */
            stay_date: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LowDemandResponse */
        LowDemandResponse: {
            /** Count */
            count: number;
            /** Rows */
            rows: components["schemas"]["LowDemandRow"][];
            /**
             * Threshold
             * @description 이 값 미만을 낮은 수요로 본다
             */
            threshold: number;
        };
        /** LowDemandRow */
        LowDemandRow: {
            /** Predicted */
            predicted: number;
            /** Property Id */
            property_id: string;
            /** Region */
            region: string;
            /**
             * Stay Date
             * Format: date
             */
            stay_date: string;
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Baseline */
            baseline: string;
            /** Measured By */
            measured_by: string;
            /** Rows */
            rows: components["schemas"]["ModelRow"][];
            /** Serving */
            serving: string;
        };
        /** ModelRow */
        ModelRow: {
            /** Folds */
            folds: number;
            /** Mae Mean */
            mae_mean: number;
            /** Model */
            model: string;
            /** Vs Baseline Pct */
            vs_baseline_pct?: number | null;
            /** Wape Mean */
            wape_mean: number;
            /** Wape Std */
            wape_std: number;
            /** Wape Worst */
            wape_worst: number;
        };
        /** SegmentResponse */
        SegmentResponse: {
            /** Model */
            model: string;
            /** Note */
            note: string;
            /** Rows */
            rows: components["schemas"]["SegmentRow"][];
        };
        /** SegmentRow */
        SegmentRow: {
            /** Mae */
            mae: number;
            /** N */
            n: number;
            /** Region */
            region: string;
            /** Rmse */
            rmse: number;
            /** Wape */
            wape: number;
            /** Zero Ratio */
            zero_ratio: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forecast_forecast_get: {
        parameters: {
            query?: {
                /** @description 지역으로 거른다 */
                region?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    low_demand_forecast_low_demand_get: {
        parameters: {
            query?: {
                /** @description 이 값 미만을 낮은 수요로 본다 */
                threshold?: number;
                region?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LowDemandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segments_forecast_segments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
}
