/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orchestration/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Orchestration Pending
         * @description 사람 승인 대기. 이미 판단한 건은 빠진다.
         */
        get: operations["orchestration_pending_orchestration_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orchestration/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Orchestration Recent
         * @description 최근 결정. **실행된 것만 보면 통제가 안 보인다.**
         */
        get: operations["orchestration_recent_orchestration_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orchestration/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Orchestration Review
         * @description 사람의 판단을 받는다. **승인해도 규칙은 그대로 걸린다.**
         *
         *     대기 건은 묵는다. 그 사이 다른 에이전트가 그 단위를 가져갔다면 사람이
         *     승인했다는 이유로 한 단위 한 개입을 건너뛸 수 없다 — 그러면 사람의 손을 거친
         *     건이 오히려 측정을 깨는 통로가 된다. 그래도 **사람의 판단은 남긴다.**
         */
        post: operations["orchestration_review_orchestration_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orchestration/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Orchestration Summary
         * @description 콘솔 첫 화면. **두 비율을 따로 낸다.**
         *
         *     예산이 모자라 거절된 제안은 "사람이 AI 를 안 믿었다" 가 아니다. 하나로 묶으면
         *     예산을 줄이는 것만으로 채택률이 떨어지고, 그 숫자를 보고 모델을 의심하게 된다.
         */
        get: operations["orchestration_summary_orchestration_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm
         * @description 고객 승인. **이 호출 없이는 상태 변경이 일어나지 않는다.**
         */
        post: operations["confirm_support_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_support_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description 열린 문의 목록.
         *
         *     `awaiting=true` 면 **사람 승인을 기다리는 것만** 준다. 콘솔의 "상담 승인"
         *     화면이 그리는 것이 그것이다 — 그 전까지는 승인할 대기 건 자체가 없어서
         *     화면 이름이 하는 말과 실제가 어긋나 있었다.
         *
         *     최근에 열린 것이 위로 온다. 오래 기다린 것을 아래에 두는 건 이상해 보이지만,
         *     대기 목록은 보통 **새로 들어온 것부터** 처리하는 화면이 아니라 훑는
         *     화면이라 그렇다. 순서를 바꿔야 할 이유가 생기면 그때 바꾼다.
         */
        get: operations["list_sessions_support_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_support_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdoptionOut
         * @description AI 권고 채택률. **사람이 판단한 것만 센다.**
         */
        AdoptionOut: {
            /** Accepted */
            accepted: number;
            /** Pending */
            pending: number;
            /** Rate */
            rate?: number | null;
            /** Reviewed */
            reviewed: number;
        };
        /** AgentOut */
        AgentOut: {
            /** Awaiting Confirmation */
            awaiting_confirmation: boolean;
            decision?: components["schemas"]["DecisionOut"] | null;
            /** Escalated */
            escalated: boolean;
            /** Response */
            response: string;
            /** Session Id */
            session_id: string;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
        };
        /** ConfirmIn */
        ConfirmIn: {
            /**
             * Approved
             * @default true
             */
            approved: boolean;
            /** Session Id */
            session_id: string;
        };
        /**
         * DecisionOut
         * @description 판단 결과. **`proceed` 에 따라 나머지 필드가 갈린다.**
         *
         *     거절이면 `reason` 만, 진행이면 환불 정보가 실린다. 한 모델로 두되 서로
         *     배타적인 필드를 선택으로 남긴다 — 소비자가 `proceed` 를 보고 갈라야 한다는
         *     사실이 스키마에 드러나야 하기 때문이다. `dict` 로 두면 그 사실이 사라지고,
         *     화면은 환불 금액이 항상 있다고 가정하게 된다.
         */
        DecisionOut: {
            /** Policy */
            policy?: string | null;
            /** Proceed */
            proceed: boolean;
            /** Reason */
            reason?: string | null;
            /** Refund Amount */
            refund_amount?: number | null;
            /** Refund Ratio */
            refund_ratio?: number | null;
        };
        /**
         * DecisionRow
         * @description 원장 한 줄. **거절 사유가 필수다** — 이유 없는 거절은 콘솔에서 쓸모가 없다.
         */
        DecisionRow: {
            /** Action */
            action: string;
            /** Agent */
            agent: string;
            /** Cost */
            cost: number;
            /** Decision */
            decision: string;
            /** Human Decision */
            human_decision?: string | null;
            /** Id */
            id: number;
            /** Reason */
            reason: string;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Unit */
            unit: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageIn */
        MessageIn: {
            /** Booking Id */
            booking_id?: string | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Session Id */
            session_id: string;
        };
        /** ReviewIn */
        ReviewIn: {
            /** Approve */
            approve: boolean;
            /** Intervention Id */
            intervention_id: number;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Reviewer */
            reviewer: string;
        };
        /** ReviewOut */
        ReviewOut: {
            /** Blocked */
            blocked?: string | null;
            /** Error */
            error?: string | null;
            /** Executed */
            executed?: boolean | null;
            /** Final Decision */
            final_decision?: string | null;
            /** Human Decision */
            human_decision?: string | null;
            /** Intervention Id */
            intervention_id?: number | null;
            /** Ok */
            ok: boolean;
        };
        /**
         * SessionOut
         * @description 세션 현재 상태.
         *
         *     예전에는 `dict` 를 그대로 돌려줬다. 그러면 OpenAPI 에 모양이 안 실리고,
         *     소비자는 응답 모양을 손으로 적을 수밖에 없다 — 그렇게 적힌 것은 서비스가
         *     바뀌어도 아무 데서도 안 걸린다.
         */
        SessionOut: {
            /** Awaiting Confirmation */
            awaiting_confirmation: boolean;
            decision?: components["schemas"]["DecisionOut"] | null;
            /** Escalated */
            escalated: boolean;
            /** Next Nodes */
            next_nodes: string[];
            /** Response */
            response: string;
            /** Session Id */
            session_id: string;
            /** Trace */
            trace: components["schemas"]["TraceEntry"][];
        };
        /**
         * SessionSummary
         * @description 세션 한 줄. 콘솔의 대기 목록이 쓴다.
         */
        SessionSummary: {
            /** Awaiting Confirmation */
            awaiting_confirmation: boolean;
            /** Booking Id */
            booking_id?: string | null;
            /** Escalated */
            escalated: boolean;
            /** Last Message */
            last_message: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Response */
            response: string;
            /** Session Id */
            session_id: string;
        };
        /** SummaryOut */
        SummaryOut: {
            adoption: components["schemas"]["AdoptionOut"];
            /** By Agent */
            by_agent: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Policy Pass Rate */
            policy_pass_rate?: number | null;
            /** Spent */
            spent: number;
        };
        /**
         * TraceEntry
         * @description 트레이스 한 줄.
         *
         *     **`node` 만 보장한다.** 나머지 키는 노드마다 다르고, 노드가 늘면 또 달라진다.
         *     전부 열거하면 노드를 하나 추가할 때마다 스키마가 따라 움직여야 하고, 그렇다고
         *     통째로 `dict` 로 두면 소비자가 `node` 조차 믿을 수 없다. 보장되는 것만
         *     보장하고 나머지는 열어 둔다.
         */
        TraceEntry: {
            /** Node */
            node: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    orchestration_pending_orchestration_pending_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orchestration_recent_orchestration_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                decision?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orchestration_review_orchestration_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orchestration_summary_orchestration_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
        };
    };
    confirm_support_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_support_messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_support_sessions_get: {
        parameters: {
            query?: {
                awaiting?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_support_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
